from setuptools import setup

setup(
    name='prairieviewreader',
    version="0.1.0",
    description="A package to read metadata generated by Bruker PrairieView Calcium Imaging acquisition system",
    url="https://github.com/kushalbakshi/prairieview-reader",
    author="Kushal Bakshi",
    author_email="kushalbakshi@gmail.com",
    license="GPL",
    install_requires = ["numpy"],
    packages=["prairieviewreader"],
)
